ランチャーに対戦機能追加
codeforkosen/Kakomimasu pull request #180
Opened 2021-06-09 16:05 UTC by ninja03

* AIを選んで「対戦する」を押すとブラウザが開きます
* ローカルで対戦を試すためclient_denoの接続先をlocalhostにしました
![image](https://user-images.githubusercontent.com/69106571/121389468-6956db80-c987-11eb-989a-2900b67e69b9.png)

2021-06-10 13:50 UTC, kamekyame requested changes
PRありがとうございます🙇
対戦しやすくなって便利になりました。

ただ、僕の環境では処理が早すぎるせいか、
```javascript
shell.ShellExecute('deno', 'run -A client_deno/' + p1.value);
shell.ShellExecute('deno', 'run -A client_deno/' + p2.value);
```
の部分でそれぞれのクライアントが別のゲームに入ってしまう場合がありました。
2つ目の`ShellExecute`を`setTimeout`を使っていくらか遅らすと上手くいくようです。
```javascript
shell.ShellExecute('deno', 'run -A client_deno/' + p1.value);
setTimeout(function() {
      shell.ShellExecute('deno', 'run -A client_deno/' + p2.value);
},100)   
```
この部分の修正お願いしてもいいですか？

あとこちらは提案ですが、`defaulthost`は元のままにしておいて、下のようにクライアントを起動時に`--local`オプションを付けるのはどうでしょうか？
```javascript
shell.ShellExecute('deno', 'run -A client_deno/' + p1.value + ' --local');
```

2021-06-10 22:24 UTC, ninja03 commented
環境によって動作が変わる発見
ありがとうございます🙇
setTimeoutで待つようにします

ローカル対戦をするとき
--localオプションで接続先変更を忘れていました
ありがとうございます
修正します🙇

2021-06-11 13:34 UTC, ninja03 commented
修正しました！

2021-06-11 14:55 UTC, kamekyame approved these changes
ありがとうございます

2021-06-11 14:55 UTC, merged