コアだけ残しました
codeforkosen/Kakomimasu pull request #273
Opened 2021-09-10 13:14 UTC by ninja03

2021-09-10 15:43 UTC, kamekyame requested changes
ありがとうございます🙇

- imgフォルダ内のロゴはserverリポジトリの方には写してないので、新規リポジトリを作る。
- READMEの「コアの利用方法」を移動したmain.jsに対応させる。

以上の点について修正お願いしてもいいですか？

2021-09-10 21:12 UTC, ninja03 commented
ありがとうございます
修正しました

2021-09-11 03:19 UTC, kamekyame requested changes
修正ありがとうございます。
main.js内のimportも直していただいてもいいですか？

2021-09-11 13:02 UTC, ninja03 commented
サンプル修正しました

2021-09-11 16:05 UTC, kamekyame approved these changes
LGTM:+1:

2021-09-11 16:05 UTC, merged